name: sea_battle
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  http: ^0.13.4
  sea_battle_entity:
    path: packages/sea_battle_entity
  sea_battle_model:
    path: packages/sea_battle_model
  sea_battle_domain:
    path: packages/sea_battle_domain
  sea_battle_mapper:
    path: packages/sea_battle_mapper
  sea_battle_api:
    path: packages/sea_battle_api
  sea_battle_repository:
    path: packages/sea_battle_repository
  sea_battle_presentation:
    path: packages/sea_battle_presentation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - .env